@baseUrl = http://localhost:5031/matches

POST {{baseUrl}}
content-type: application/json

{
    "playerId": "player1"
}

###
GET {{baseUrl}}?playerId=player2

###
GET {{baseUrl}}/1

###
PUT {{baseUrl}}/1
content-type: application/json

{
    "ipAddress": "192.168.1.1",
    "port": 5555
}

###
DELETE {{baseUrl}}/